---
# Remove CouchDB server

- name: remove CouchDB
  docker:
    name: couchdb
    image: couchdb
    state: absent
  ignore_errors: True

# TODO: remove this once we drop ant
- name: remove database env file
  file:
    path: "{{ openwhisk_home }}/{{ db_provider|lower }}-local.env"
    state: absent