---
# This role will initialize the immortal DBs in the database account.
# This step is usually done only once per account.

# Same as cloudant, so include here.

- include: "{{ openwhisk_home }}/ansible/roles/cloudant/tasks/initdb.yml"
