---
# This playbook deploys an Openwhisk stack.  
# It assumes you have already set up your database with the respective db provider playbook (currently cloudant.yml or couchdb.yml)

- hosts: ansible
  roles:
  - predeploy

- include: consul.yml

- include: kafka.yml

- include: controller.yml

- include: activator.yml

- include: invoker.yml

- include: edge.yml

- hosts: ansible
  roles:
  - postdeploy